package io.github.fanfeast.anonpdf.ui.theme

import androidx.compose.ui.graphics.Color

// Brand: deep navy paper with a single blue accent. Two colours, no gradients.
val Navy900 = Color(0xFF14213D)
val Blue600 = Color(0xFF2F81F7)
val Blue200 = Color(0xFFA9CBFF)

val LightPrimary = Color(0xFF1B5FC1)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD8E5FF)
val LightOnPrimaryContainer = Color(0xFF001B3D)
val LightSecondary = Color(0xFF545F71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD8E3F8)
val LightOnSecondaryContainer = Color(0xFF111C2B)
val LightBackground = Color(0xFFFCFCFF)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFCFCFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFE0E2EC)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF74777F)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

val DarkPrimary = Color(0xFFACC7FF)
val DarkOnPrimary = Color(0xFF002F63)
val DarkPrimaryContainer = Color(0xFF00458B)
val DarkOnPrimaryContainer = Color(0xFFD8E5FF)
val DarkSecondary = Color(0xFFBCC7DB)
val DarkOnSecondary = Color(0xFF263141)
val DarkSecondaryContainer = Color(0xFF3C4758)
val DarkOnSecondaryContainer = Color(0xFFD8E3F8)
val DarkBackground = Color(0xFF101418)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF101418)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C6CF)
val DarkOutline = Color(0xFF8D9199)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
